In [1]:
%pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [38]:
import numpy as np

a = np.random.rand(4,4)

U, S, Vh = np.linalg.svd(a)

print(U)
print(S)
print(Vh)

[[-0.50440188  0.85844666  0.08566635 -0.03618494]
 [-0.45760437 -0.3501324   0.81728441  0.00719325]
 [-0.56119042 -0.31198957 -0.44236366 -0.62613274]
 [-0.470364   -0.20769965 -0.35919615  0.77884318]]
[2.15082184 0.6920046  0.48561361 0.18981151]
[[-0.36089401 -0.75460589 -0.34285967 -0.42751926]
 [-0.46097624 -0.19810713 -0.14260874  0.85318065]
 [-0.0471725  -0.40918339  0.9106797   0.03172052]
 [-0.80933996  0.47317277  0.18103172 -0.29715968]]


In [39]:
# print(np.matmul(Vh, np.matmul(np.diag(S).T, np.matmul(U.T, np.matmul(U, np.matmul(np.diag(S), Vh.T))))))

# print(np.matmul(Vh, np.matmul(np.diag(S).T, np.matmul(np.diag(S), Vh.T))))

symMat = np.matmul(a, a.T)

U, S, Vh = np.linalg.svd(symMat)

print(U)
print(S)
print(Vh.T)


[[-0.50440188  0.85844666  0.08566635 -0.03618494]
 [-0.45760437 -0.3501324   0.81728441  0.00719325]
 [-0.56119042 -0.31198957 -0.44236366 -0.62613274]
 [-0.470364   -0.20769965 -0.35919615  0.77884318]]
[4.62603457 0.47887037 0.23582058 0.03602841]
[[-0.50440188  0.85844666  0.08566635 -0.03618494]
 [-0.45760437 -0.3501324   0.81728441  0.00719325]
 [-0.56119042 -0.31198957 -0.44236366 -0.62613274]
 [-0.470364   -0.20769965 -0.35919615  0.77884318]]
